# Generated by Django 4.1.7 on 2023-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfashion', '0003_alter_cartdb_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_pic'),
        ),
    ]
