# Generated by Django 4.1.7 on 2023-06-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfashion', '0005_remove_cartdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
