# Generated by Django 4.1.7 on 2023-06-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfashion', '0007_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='state',
            new_name='State',
        ),
    ]
