# Generated by Django 4.1.7 on 2023-05-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(blank=True, max_length=20, null=True)),
                ('prod_name', models.CharField(blank=True, max_length=20, null=True)),
                ('prod_price', models.IntegerField(blank=True, null=True)),
                ('prod_description', models.CharField(blank=True, max_length=90, null=True)),
                ('prod_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
    ]
